name: Deploy

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Datalake
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws-region: us-east-2
    - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan
        $COMMAND_IAC apply -auto-approve
    
    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
      FILE: 'C:\Users\Lucas\Desktop\2021\microdados_educacao_basica_2020\Dados uteis\*.csv'
        AWS_REGION: 'us-east-2'
        S3_BUCKET: 'base-bucket-name'
        S3_KEY: 'raw/matricula-censo'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
